variables:
  BPT_SPLT_BY_BUILD_TYPES: "true"
  BPT_REQUIRE_MORE_DISK_SPACE: "true"
  BPT_VARIABLE_TEST: "Templates can access global variables!"

resources:
  repositories:
    - repository: templates
      type: github
      name: bincrafters/templates
      endpoint: github
      ref: azp_generate_matrix

extends:
  template: .ci/azure.yml@templates
  parameters:
    conanLoginUsername: $(CONAN_LOGIN_USERNAME)
    conanPassword: $(CONAN_PASSWORD)
